"""Regenerate the small offline lunar-month index from HKO's annual text tables.

Source: https://www.hko.gov.hk/tc/gts/time/conversion1_text.htm
The generated index is for date grounding, not statutory holiday schedules.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
import re
from urllib.request import urlopen


FIRST_YEAR = 2023  # Carry the preceding lunar month into January 2024.
LAST_YEAR = 2050
OUTPUT = Path(__file__).parents[1] / "runtime" / "_chinese_calendar_data.py"
ROW = re.compile(r"^(\d{4})年(\d{1,2})月(\d{1,2})日\s+(\S+)\s+星期\S+(?:\s+(\S+))?")
MONTHS = {name: number for number, name in enumerate(
    ("正", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二"), 1
)}


def main() -> None:
    starts: list[tuple[str, int, bool]] = []
    qingming: dict[int, str] = {}
    for year in range(FIRST_YEAR, LAST_YEAR + 1):
        url = f"https://www.hko.gov.hk/tc/gts/time/calendar/text/files/T{year}c.txt"
        with urlopen(url, timeout=30) as response:
            rows = response.read().decode("utf-8-sig").splitlines()
        count = 0
        for row in rows:
            match = ROW.match(row)
            if match is None:
                continue
            y, month, day = map(int, match.group(1, 2, 3))
            solar_day = date(y, month, day)
            count += 1
            lunar_label = match.group(4)
            if lunar_label.endswith("月"):
                is_leap = lunar_label.startswith("閏")
                month_name = lunar_label.removeprefix("閏").removesuffix("月")
                if month_name not in MONTHS:
                    raise ValueError(f"Unknown lunar month {lunar_label!r} in {url}")
                starts.append((solar_day.isoformat(), MONTHS[month_name], is_leap))
            if match.group(5) == "清明":
                qingming[year] = solar_day.isoformat()
        expected = (date(year + 1, 1, 1) - date(year, 1, 1)).days
        if count != expected or year not in qingming:
            raise ValueError(f"Incomplete HKO table for {year}: {count} days")

    lines = [
        '"""Offline month starts and Qingming dates from Hong Kong Observatory tables.',
        '',
        'Source: https://www.hko.gov.hk/tc/gts/time/conversion1_text.htm',
        'Generated by tools/build_chinese_calendar_data.py. Do not edit by hand.',
        '"""',
        '',
        'LUNAR_MONTH_STARTS = (',
    ]
    lines.extend(f'    ({day!r}, {month}, {leap}),' for day, month, leap in starts)
    lines.extend((')', '', 'QINGMING_DATES = {'))
    lines.extend(f'    {year}: {day!r},' for year, day in qingming.items())
    lines.extend(('}', ''))
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(starts)} lunar month starts, {len(qingming)} Qingming dates to {OUTPUT}")


if __name__ == "__main__":
    main()
