"""Compile the finite error catalog used by the telemetry wire contract."""
import ast
import inspect
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def codes():
    from runtime.personal_chat.service import JEV_ERROR_CODES
    from runtime.personal_chat.backend import _generation_failure_code
    from runtime.diagnostics.failure_context import CODES, REWRITE_ERROR_CODES
    result = set(JEV_ERROR_CODES)
    for path in (ROOT / 'runtime/personal_chat').glob('*.py'):
        for node in ast.walk(ast.parse(path.read_text(encoding='utf-8'))):
            if (isinstance(node, ast.Constant) and isinstance(node.value, str)
                    and re.fullmatch(r'(?:QQ|PERSONAL_CHAT)_[A-Z0-9_]*[A-Z0-9]', node.value)):
                result.add(node.value)
    source = ast.parse(inspect.getsource(_generation_failure_code))
    fixed = {node.value for node in ast.walk(source) if isinstance(node, ast.Constant)
             and isinstance(node.value, str) and re.fullmatch(r'[A-Z][A-Z0-9_]*[A-Z0-9]', node.value)}
    result.update(_generation_failure_code(code) for code in fixed | CODES | REWRITE_ERROR_CODES)
    return sorted(result)


def main():
    values = codes()
    (ROOT / 'runtime/diagnostics/telemetry_codes.py').write_text(
        '# Generated by scripts/generate_reply_telemetry_codes.py.\nERROR_CODES = frozenset({\n'
        + ''.join('    ' + repr(value) + ',\n' for value in values) + '})\n', encoding='utf-8')
    (ROOT / 'contracts/reply_telemetry_codes.json').write_text(json.dumps(values, indent=2) + '\n', encoding='utf-8')
    path = ROOT / 'contracts/reply_telemetry_v2.schema.json'
    schema = json.loads(path.read_text(encoding='utf-8'))
    schema['properties']['events']['items']['properties']['error_code']['enum'] = ['NONE', 'UNKNOWN', *values]
    path.write_text(json.dumps(schema, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
